3.5
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
# Package imports
import numpy as np
import matplotlib.pyplot as plt
from testCases import *
import sklearn
import sklearn.datasets
import sklearn.linear_model
from planar_utils import plot_decision_boundary, sigmoid, load_planar_dataset, load_extra_datasets

%matplotlib inline

np.random.seed(1) # set a seed so that the results are consistent
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-00ee9d93e151>[0m in [0;36m<module>[0;34m()[0m
[1;32m      4[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0;32mfrom[0m [0mtestCases[0m [0;32mimport[0m [0;34m*[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0;32mimport[0m [0msklearn[0m[0;34m[0m[0m
[1;32m      8[0m [0;32mimport[0m [0msklearn[0m[0;34m.[0m[0mdatasets[0m[0;34m[0m[0m

[0;31mImportError[0m: No module named 'testCases'
ImportError: No module named 'testCases'

Executability                            : False
