3.6
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
## import the python modules to use
from mpl_toolkits.basemap import Basemap
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import pandas as pd
import pylab as pl
import matplotlib.pyplot as plt
%matplotlib inline
df = pd.read_csv('Downloads/All_Starbucks_Locations_in_the_World.csv', header = 0)
##import the dataset, panda function read the data

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-36ac724596f3>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mwarnings[0m[0;34m.[0m[0mfilterwarnings[0m[0;34m([0m[0;34m'ignore'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;31m## import the python modules to use[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mfrom[0m [0mmpl_toolkits[0m[0;34m.[0m[0mbasemap[0m [0;32mimport[0m [0mBasemap[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;32mimport[0m [0mplotly[0m[0;34m.[0m[0mplotly[0m [0;32mas[0m [0mpy[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;32mimport[0m [0mplotly[0m[0;34m.[0m[0mgraph_objs[0m [0;32mas[0m [0mgo[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'mpl_toolkits.basemap'
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

Executability                            : False
